version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DB_LANG=ja_JP
    volumes:
      - pgsqldb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: example

volumes:
  pgsqldb:
    driver: local